name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  stable:
    name: Build and test on stable
    strategy:
      matrix:
        os: [ "ubuntu-22.04" ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install mongodb
        run: |
          sudo cp .github/workflows/mongodb-org-7.0.gpg /usr/share/keyrings/
          sudo cp .github/workflows/mongodb-org-7.0.list /etc/apt/sources.list.d/
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends mongodb-org-server
      - name: Install latest stable Rust toolchain
        run: |
          rustup install stable
          rustup default stable
      - name: Build (tokio)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --color=always --all-targets
      - name: Test (tokio)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --color=always
      - name: Build (async-std)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --color=always --no-default-features --features async-std-runtime --all-targets
      - name: Test (async-std)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --color=always --no-default-features --features async-std-runtime

  windows:
    name: Build and test on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Cache cargo registry
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install MongoDB
        run: choco install mongodb --version 4.4.6
      - name: Create MongoDB data and log directories
        run: |
          New-Item -ItemType Directory -Path C:\data\db -Force
          New-Item -ItemType Directory -Path C:\data\log -Force
      - name: Start MongoDB Service
        run: |
          Set-Service -Name MongoDB -StartupType Automatic
          Start-Service -Name MongoDB
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-targets
      - name: Run tests
        uses: actions-rs/cargo
